- name: Organization
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.organization.svg
    user: github
    token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
    base: header, repositories

- name: Large display
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.large.svg
    token: ${{ secrets.METRICS_TOKEN }}
    config_display: large

- name: JSON metrics
  if: ${{ success() || failure() }}
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.example.json
    token: ${{ secrets.METRICS_TOKEN }}
    config_output: json

- name: PNG metrics
  if: ${{ success() || failure() }}
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.example.png
    token: ${{ secrets.METRICS_TOKEN }}
    config_output: png

- name: Metrics insights
  if: ${{ success() || failure() }}
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.insights.html
    token: ${{ secrets.METRICS_TOKEN }}
    config_output: insights

- name: Presets
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.presets.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: header, repositories
    config_presets: https://raw.githubusercontent.com/lowlighter/metrics/presets/lunar-red/preset.yaml
  prod:
    skip: true
  test:
    modes:
      - web

- name: Plugin error example
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.error.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_projects: yes
  prod:
    with:
      plugins_errors_fatal: no
  test:
    skip: true
    
- name: Full-year calendar
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.isocalendar.fullyear.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_isocalendar: yes
    plugin_isocalendar_duration: full-year


- name: Metrics
  on:
    # Schedule daily updates
    schedule: [{cron: "0 0 * * *"}]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: {branches: ["master", "main"]}
  jobs:
    github-metrics:
      runs-on: ubuntu-latest
      environment: 
        name: production
      permissions:
        contents: write
      steps:
        - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

